{"uuid": "4b638f62-e0ed-496d-8e06-063c3efb2da5", "children": ["9632fc05-28f3-4cbe-8715-63907bd59279", "b64ba600-739a-4ea9-bb76-5309741bea5a", "666b51da-76a6-4e29-8fd3-0ebaf3418552", "eb6a97b2-ce12-4081-8a7f-a35e8ef0dd16"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"D:\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Projects\\Ktp\\tests\\conftest.py\", line 17, in browser\n    driver = webdriver.chrome(executable_path=r\"C:\\Users\\Administrator\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe\", options=chrome_options)\n"}, "start": 1594900804417, "stop": 1594900804417}], "start": 1594900804417, "stop": 1594900804493}